[package]
name = "aodv"
version = "0.1.0"
edition = "2021"
description = "Ad-Hoc On-Demand Distance Vector protocol implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
socket2 = "0.4.0"
